services:
  httpreq:
    image: zzci/httpreq:latest
    container_name: httpreq
    restart: unless-stopped
    ports:
      - "53:53"
      - "53:53/udp"
      - "3000:3000"
    volumes:
      - ./data:/app/data
